### ISSUE TITLE
@v1 pulls old version

### ISSUE THREAD

**Issue by cablespaghetti** [abronin/ecr-retag-action#4]
I initially followed the readme and used @v1 however because there is an old tag with that name it doesn't do the usual semantic versioning thing of downloading the latest i.e. v1.5.0. Maybe deleting the old tag would help this problem?

**Comment by abronin** [comment]
Fixed. Thanks for reporting!

**Comment by techieyann** [comment]
sorry to comment on a closed issue, but felt minimal enough to not warrant a new one:

@v1 is still pointing to v1.6, it should be updated to v1.7 now that it is released

**Comment by abronin** [comment]
thank you @techieyann! it should be fixed now.
